// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const createPinia: typeof import('pinia')['createPinia']
  const createRouter: typeof import('~/router')['createRouter']
  const createSSRApp: typeof import('vue')['createSSRApp']
  const devalue: typeof import('@nuxt/devalue')['devalue']
  const head: typeof import('@vueuse/head')['head']
  const ref: typeof import('vue')['ref']
  const usePageStore: typeof import('~/store/page')['usePageStore']
  const useSSRContext: typeof import('vue')['useSSRContext']
}
export {}
