// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const apiGetPage: typeof import('~/api/apiPage')['apiGetPage']
  const computed: typeof import('vue')['computed']
  const createHead: typeof import('@vueuse/head')['createHead']
  const createPinia: typeof import('pinia')['createPinia']
  const createRouter: typeof import('~/router')['createRouter']
  const createSSRApp: typeof import('vue')['createSSRApp']
  const defineComponent: typeof import('vue')['defineComponent']
  const devalue: typeof import('@nuxt/devalue')['devalue']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const useHead: typeof import('@vueuse/head')['useHead']
  const usePageStore: typeof import('~/store/page')['usePageStore']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useSSRContext: typeof import('vue')['useSSRContext']
}
export {}
