// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./components/Header.vue')['default']
    Test01: typeof import('./components/Test01.vue')['default']
    Test02: typeof import('./components/Test02.vue')['default']
  }
}

export { }
